security:
    encoders:
        App\Entity\Utilisateur: plaintext

    providers:
         our_db_provider:
            entity:
                class: App\Entity\Utilisateur
                property: username

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            provider: our_db_provider
    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }