<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAkn2poA\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAkn2poA/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAkn2poA.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAkn2poA\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerAkn2poA\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Akn2poA',
    'container.build_id' => 'd7ba3f79',
    'container.build_time' => 1519665384,
));
