<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRy2snxa\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRy2snxa/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRy2snxa.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRy2snxa\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerRy2snxa\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ry2snxa',
    'container.build_id' => '7bc05a98',
    'container.build_time' => 1520258400,
));
