<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY3foT70\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY3foT70/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerY3foT70.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerY3foT70\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerY3foT70\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Y3foT70',
    'container.build_id' => '8cdec220',
    'container.build_time' => 1520262242,
));
