<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU1qKDju\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU1qKDju/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerU1qKDju.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerU1qKDju\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerU1qKDju\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'U1qKDju',
    'container.build_id' => '2ae32d70',
    'container.build_time' => 1520264013,
));
